server:
  port: 8102


spring:
  application:
      name: tangtang
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/graproject?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.163.com
    username: sexytlh@163.com
    password: 215fg78910dj
    default-encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
#  thymeleaf:
#      cache: false
#      mode: HTML5
#      encoding: UTF-8
#      content-type: text/html

mybatis:
    mapper-locations: classpath:mapper/*.xml

#设置静态资源路径，多个以逗号分隔
spring.resources.static-locations: classpath:static/,file:static/

logging:
#  path: ${user.home}/logs
#
  file: ${user.home}/logs/${spring.application.name}.log

